--- #YAML:1.0
name:                Fuse
version:             0.09_2
abstract:            write filesystems in Perl using FUSE
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Mark Glines <mark@glines.org>
