--- #YAML:1.0
name:               Fuse
version:            0.12
abstract:           write filesystems in Perl using FUSE
author:
    - Mark Glines <mark@glines.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
resources:
    bugtracker:  https://rt.cpan.org/Public/Dist/Display.html?Name=Fuse
    repository:  http://github.com/dpavlin/perl-fuse
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
