---
abstract: 'write filesystems in Perl using FUSE'
author:
  - 'Mark Glines <mark@glines.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Fuse
no_index:
  directory:
    - t
    - inc
requires:
  Filesys::Statvfs: 0
  Lchown: 0
  Unix::Mknod: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Fuse
  license: http://www.gnu.org/licenses/lgpl-2.1.html
  repository: http://github.com/dpavlin/perl-fuse
version: 0.16
