--- #YAML:1.0
name:               Fuse
version:            0.16_1
abstract:           write filesystems in Perl using FUSE
author:
    - Mark Glines <mark@glines.org>
license:            LGPL_2_1
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Filesys::Statvfs:  0
    Lchown:            0
    Unix::Mknod:       0
resources:
    bugtracker:  https://rt.cpan.org/Public/Dist/Display.html?Name=Fuse
    license:     http://www.gnu.org/licenses/lgpl-2.1.html
    repository:  http://github.com/dpavlin/perl-fuse
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
